---
- name: Run CIS Hardening to Ubuntu 20.04 for CIS Level 1 - Server | Compliance and Risk
  hosts: all
  become: yes
  roles:
    - cnr-hardening-ubuntu-20.04-v1
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ubuntu_2004_cis_firewall: ufw

    # DISABLE 1.1.1.6 as it results with error | modprobe: FATAL: Module squashfs is builtin.
    ubuntu_2004_cis_section1_rule_1_1_1_6: false
...

