---
# tasks file for Preliminary Appliance Actions

- name: "Install python3-apt"
  apt:
    name: python3-apt
    state: present
  when: preliminary_appliance

- name: "Gather Package facts"
  package_facts:
    manager: apt
  when: preliminary_appliance

- name: "Update repository cache"
  apt:
    update_cache: yes
  when: preliminary_appliance

- name: "Import Variables Files"
  include_vars: "{{ item }}"
  with_items:
    - "{{ playbook_dir }}/cnr-hardening-ubuntu-20.04-v1/vars/section_01.yml"
    - "{{ playbook_dir }}/cnr-hardening-ubuntu-20.04-v1/vars/section_02.yml"
    - "{{ playbook_dir }}/cnr-hardening-ubuntu-20.04-v1/vars/section_03.yml"
    - "{{ playbook_dir }}/cnr-hardening-ubuntu-20.04-v1/vars/section_04.yml"
    - "{{ playbook_dir }}/cnr-hardening-ubuntu-20.04-v1/vars/section_05.yml"
    - "{{ playbook_dir }}/cnr-hardening-ubuntu-20.04-v1/vars/section_06.yml"
  when: preliminary_appliance